### PR TITLE
Remove usage of URL from `fileExists()`

### LINKED ISSUE #232: Search for ansible config file fails return an exception for 'INVALID_URL'
I discovered this bug while writing the test for `doValidation`.

While performing validation using ansible-lint, the code searches for `.ansible-lint` config file but rather than returning the existence of the file in true or false, it fails with an exception of 'INVALID_URL'.

On debugging, I found that the problem was caused by the `fileExists()` in `misc.ts` (https://github.com/ansible/ansible-language-server/blob/main/src/utils/misc.ts).

### PR DESCRIPTION
**Pull request by priyamsahoo**
- The PR resolves #232.
- `fs.stat()` requires only the file or directory uri in the string form. So, casting of the file uri to URL seems unnecessary and also prevents unnecessary failures.

### CODE REVIEW

**Comment by tomaciazek** [comment]
Good find! Perhaps we could get rid of `URL` also in `src/services/metadataLibrary.ts`?

**Review by ganeshrn — APPROVED** [review]

File: src/utils/misc.ts [hunk 1]
```diff
@@ -1,13 +1,12 @@
 import * as child_process from 'child_process';
 import { promises as fs } from 'fs';
-import { URL } from 'url';
 import { promisify } from 'util';
 import { TextDocument } from 'vscode-languageserver-textdocument';
 import { Range } from 'vscode-languageserver-types';
 import * as path from 'path';
 
 export async function fileExists(fileUri: string): Promise<boolean> {
```
Comment (ganeshrn) [inline src/utils/misc.ts:8]: Please check if the calling function  passes `fileUri` or `filePath`

Comment (ganeshrn) [reply src/utils/misc.ts:8]: If it is file path the `fileUri` parameter can be renamed to `filepath` to avoid confusion

Comment (priyamsahoo) [reply src/utils/misc.ts:8]: It is passing fileUri as a string

**Comment by priyamsahoo** [comment]
@ganeshrn, while debugging, I found that `fs.stat()` and `fs.readFile()` can accept inputs as string with both the representations for file URI:
- file:///home/../../..
- /home/../../..

So, it's safe to remove `new URL()` from the code and simply pass the string variable representing the file URI to `fs.stat()` or `fs.readFile()`

**Comment by priyamsahoo** [comment]
> Good find! Perhaps we could get rid of `URL` also in `src/services/metadataLibrary.ts`?

Sure. Since, they both ( fs.stat() and fs.readFile() ) accept strings with both representation of file URI (with and without `file://`), it is safe to remove `URL` from `src/services/metadataLibrary.ts` as well.

But I will wait for some time, until I finish writing tests for `doCompletion()`. I can re-check at that time and then push a PR for it.

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
@priyamsahoo To allow this to be merged you need to add a changelog fragment. See https://github.com/ansible/ansible-language-server/pull/233/checks?check_run_id=5332768729 -- i am sure that @webknjaz will be happy to help if needed.

**Comment by webknjaz** [comment]
@priyamsahoo maybe add some negative+positive tests for this?

**Comment by priyamsahoo** [comment]
> @priyamsahoo maybe add some negative+positive tests for this?

@webknjaz, this something I discovered while I was tests. So, eventually, this will be tested in the upcoming test cases.

Plus, this is a blocker, since I am unable to write tests because of this.

**Comment by priyamsahoo** [comment]
> @priyamsahoo To allow this to be merged you need to add a changelog fragment. See [#233 (checks)](https://github.com/ansible/ansible-language-server/pull/233/checks?check_run_id=5332768729) -- i am sure that @webknjaz will be happy to help if needed.

@ssbarnea, done ! Thanks for the suggestion.

File: docs/changelog-fragments.d/233.bugfix.md [hunk 2]
```diff
@@ -0,0 +1,2 @@
+Fixed source of INVALID_URL type error that occurred during the search for
```
Comment (webknjaz) [inline docs/changelog-fragments.d/233.bugfix.md:1]: Since this is an identifier, let's use Markdown syntax to show that.
```suggestion
Fixed source of `INVALID_URL` type error that occurred during the search for
```

Comment (priyamsahoo) [reply docs/changelog-fragments.d/233.bugfix.md]: Thanks for the suggestion. Updated !

**Comment by ganeshrn** [comment]
> @ganeshrn, while debugging, I found that `fs.stat()` and `fs.readFile()` can accept inputs as string with both the representations for file URI:
> 
> * file:///home/../../..
> * /home/../../..
> 
> So, it's safe to remove `new URL()` from the code and simply pass the string variable representing the file URI to `fs.stat()` or `fs.readFile()`

Even though it accepts inputs as a string with both file URI and file path the function returns the different output.
For example:
Snippet 1:
```
  const isFileExist = !!(await fs.stat(new URL(fileUri)).catch(() => false));
  console.log(`${fileUri} ${isFileExist}`);
```
Output
```
file:///Users/ganeshrn/Documents/roles/cisco_ios/meta/main.yml true
```

Snippet 2:
```
  const isFileExistNew = !!(await fs.stat(fileUri).catch(() => false));
  console.log(`${fileUri} ${isFileExistNew}`);
```
Output
```
file:///Users/ganeshrn/Documents/roles/cisco_ios/meta/main.yml false
```

As per your suggestion, the output of the second snippet should the `true` as well but that's not the case here.

**Comment by ganeshrn** [comment]
After applying the below patch as suggested by @tomaciazek in his comment https://github.com/ansible/ansible-language-server/pull/233#issuecomment-1049888905 it works as expected for the role meta-file scenario.
```
% git diff  src/services/metadataLibrary.ts
diff --git a/src/services/metadataLibrary.ts b/src/services/metadataLibrary.ts
index 7b65d83..3d346dc 100644
--- a/src/services/metadataLibrary.ts
+++ b/src/services/metadataLibrary.ts
@@ -1,5 +1,5 @@
 import { promises as fs } from 'fs';
-import { URL } from 'url';
+import { URI } from 'vscode-uri';
 import { Connection } from 'vscode-languageserver';
 import { DidChangeWatchedFilesParams } from 'vscode-languageserver-protocol';
 import { parseAllDocuments } from 'yaml';
:...skipping...
diff --git a/src/services/metadataLibrary.ts b/src/services/metadataLibrary.ts
index 7b65d83..3d346dc 100644
--- a/src/services/metadataLibrary.ts
+++ b/src/services/metadataLibrary.ts
@@ -1,5 +1,5 @@
 import { promises as fs } from 'fs';
-import { URL } from 'url';
+import { URI } from 'vscode-uri';
 import { Connection } from 'vscode-languageserver';
 import { DidChangeWatchedFilesParams } from 'vscode-languageserver-protocol';
 import { parseAllDocuments } from 'yaml';
@@ -64,9 +64,10 @@ export class MetadataLibrary {
       source: metadataUri,
       collections: new Array<string>(),
     };
-    if (await fileExists(metadataUri)) {
+    const metadataFilePath = URI.parse(metadataUri).path
+    if (await fileExists(metadataFilePath)) {
       try {
-        const metaContents = await fs.readFile(new URL(metadataUri), {
+        const metaContents = await fs.readFile(metadataFilePath, {
           encoding: 'utf8',
         });
         parseAllDocuments(metaContents).forEach((metaDoc) => {
```

**Comment by priyamsahoo** [comment]
> After applying the below patch as suggested by @tomaciazek in his comment [#233 (comment)](https://github.com/ansible/ansible-language-server/pull/233#issuecomment-1049888905) it works as expected for the role meta-file scenario.
> 
> ```
> % git diff  src/services/metadataLibrary.ts
> diff --git a/src/services/metadataLibrary.ts b/src/services/metadataLibrary.ts
> index 7b65d83..3d346dc 100644
> --- a/src/services/metadataLibrary.ts
> +++ b/src/services/metadataLibrary.ts
> @@ -1,5 +1,5 @@
>  import { promises as fs } from 'fs';
> -import { URL } from 'url';
> +import { URI } from 'vscode-uri';
>  import { Connection } from 'vscode-languageserver';
>  import { DidChangeWatchedFilesParams } from 'vscode-languageserver-protocol';
>  import { parseAllDocuments } from 'yaml';
> :...skipping...
> diff --git a/src/services/metadataLibrary.ts b/src/services/metadataLibrary.ts
> index 7b65d83..3d346dc 100644
> --- a/src/services/metadataLibrary.ts
> +++ b/src/services/metadataLibrary.ts
> @@ -1,5 +1,5 @@
>  import { promises as fs } from 'fs';
> -import { URL } from 'url';
> +import { URI } from 'vscode-uri';
>  import { Connection } from 'vscode-languageserver';
>  import { DidChangeWatchedFilesParams } from 'vscode-languageserver-protocol';
>  import { parseAllDocuments } from 'yaml';
> @@ -64,9 +64,10 @@ export class MetadataLibrary {
>        source: metadataUri,
>        collections: new Array<string>(),
>      };
> -    if (await fileExists(metadataUri)) {
> +    const metadataFilePath = URI.parse(metadataUri).path
> +    if (await fileExists(metadataFilePath)) {
>        try {
> -        const metaContents = await fs.readFile(new URL(metadataUri), {
> +        const metaContents = await fs.readFile(metadataFilePath, {
>            encoding: 'utf8',
>          });
>          parseAllDocuments(metaContents).forEach((metaDoc) => {
> ```

Thanks for pointing it out. Fixed now !
